import { CelestialObject, ObservationLog, PlannerSlot } from "./types";

export const celestialObjects: CelestialObject[] = [
  { id: "sirius", name: "Sirius", type: "star", constellation: "Canis Major", magnitude: -1.46, distance: 8.6, spectralClass: "A", ra: "06h 45m", dec: "-16° 43'", description: "The brightest star in the night sky, a white main-sequence star in Canis Major." },
  { id: "betelgeuse", name: "Betelgeuse", type: "star", constellation: "Orion", magnitude: 0.42, distance: 700, spectralClass: "M", ra: "05h 55m", dec: "+07° 24'", description: "A red supergiant nearing the end of its life, one of the largest stars visible to the naked eye." },
  { id: "vega", name: "Vega", type: "star", constellation: "Lyra", magnitude: 0.03, distance: 25, spectralClass: "A", ra: "18h 36m", dec: "+38° 47'", description: "A bright white star and former pole star, part of the Summer Triangle asterism." },
  { id: "rigel", name: "Rigel", type: "star", constellation: "Orion", magnitude: 0.13, distance: 860, spectralClass: "B", ra: "05h 14m", dec: "-08° 12'", description: "A blue-white supergiant marking the foot of Orion the Hunter." },
  { id: "aldebaran", name: "Aldebaran", type: "star", constellation: "Taurus", magnitude: 0.86, distance: 65, spectralClass: "K", ra: "04h 35m", dec: "+16° 30'", description: "An orange giant star forming the eye of Taurus the Bull." },
  { id: "jupiter", name: "Jupiter", type: "planet", constellation: "Taurus", magnitude: -2.5, distance: 0.00008, ra: "04h 12m", dec: "+20° 15'", description: "The largest planet in the solar system, known for its Great Red Spot and prominent cloud bands." },
  { id: "saturn", name: "Saturn", type: "planet", constellation: "Aquarius", magnitude: 0.7, distance: 0.00015, ra: "23h 05m", dec: "-08° 40'", description: "The ringed planet, easily recognized through any telescope by its spectacular ring system." },
  { id: "mars", name: "Mars", type: "planet", constellation: "Gemini", magnitude: 0.9, distance: 0.00005, ra: "07h 30m", dec: "+24° 10'", description: "The Red Planet, showing polar ice caps and surface features in larger telescopes." },
  { id: "andromeda", name: "Andromeda Galaxy", type: "galaxy", constellation: "Andromeda", magnitude: 3.4, distance: 2537000, ra: "00h 42m", dec: "+41° 16'", description: "The nearest major galaxy to the Milky Way, visible to the naked eye under dark skies." },
  { id: "whirlpool", name: "Whirlpool Galaxy", type: "galaxy", constellation: "Canes Venatici", magnitude: 8.4, distance: 23000000, ra: "13h 29m", dec: "+47° 11'", description: "A grand-design spiral galaxy interacting with a smaller companion galaxy." },
  { id: "sombrero", name: "Sombrero Galaxy", type: "galaxy", constellation: "Virgo", magnitude: 8.0, distance: 29000000, ra: "12h 39m", dec: "-11° 37'", description: "An unusual galaxy with a bright nucleus and large central dust lane resembling a sombrero hat." },
  { id: "orion-nebula", name: "Orion Nebula", type: "nebula", constellation: "Orion", magnitude: 4.0, distance: 1344, ra: "05h 35m", dec: "-05° 23'", description: "One of the brightest nebulae, visible to the naked eye, a stellar nursery forming new stars." },
  { id: "ring-nebula", name: "Ring Nebula", type: "nebula", constellation: "Lyra", magnitude: 8.8, distance: 2283, ra: "18h 53m", dec: "+33° 01'", description: "A planetary nebula formed by a dying star shedding its outer layers into a ring-shaped shell." },
  { id: "crab-nebula", name: "Crab Nebula", type: "nebula", constellation: "Taurus", magnitude: 8.4, distance: 6523, ra: "05h 34m", dec: "+22° 00'", description: "A supernova remnant from the explosion observed in 1054 AD, containing a rapidly spinning pulsar." },
  { id: "eagle-nebula", name: "Eagle Nebula", type: "nebula", constellation: "Serpens", magnitude: 6.0, distance: 7000, ra: "18h 18m", dec: "-13° 49'", description: "Home to the famous Pillars of Creation, towering columns of gas and dust where stars are born." },
  { id: "pleiades", name: "Pleiades", type: "cluster", constellation: "Taurus", magnitude: 1.6, distance: 444, ra: "03h 47m", dec: "+24° 07'", description: "The Seven Sisters, a bright open cluster visible to the naked eye containing hot blue stars." },
  { id: "hercules-cluster", name: "Hercules Cluster", type: "cluster", constellation: "Hercules", magnitude: 5.8, distance: 22200, ra: "16h 41m", dec: "+36° 27'", description: "One of the brightest globular clusters in the northern sky, containing hundreds of thousands of stars." },
  { id: "double-cluster", name: "Double Cluster", type: "cluster", constellation: "Perseus", magnitude: 3.7, distance: 7500, ra: "02h 20m", dec: "+57° 08'", description: "A pair of open clusters visible to the naked eye, each containing hundreds of young stars." },
  { id: "halley", name: "Halley's Comet", type: "comet", constellation: "Orion", magnitude: 5.5, distance: 0.6, ra: "06h 10m", dec: "+10° 30'", description: "The most famous periodic comet, returning to the inner solar system every 75-79 years." },
  { id: "neowise", name: "Comet NEOWISE", type: "comet", constellation: "Ursa Major", magnitude: 3.0, distance: 0.7, ra: "12h 00m", dec: "+50° 00'", description: "A long-period comet discovered in 2020, displaying a spectacular dust and ion tail." },
  { id: "polaris", name: "Polaris", type: "star", constellation: "Ursa Minor", magnitude: 1.98, distance: 433, spectralClass: "F", ra: "02h 31m", dec: "+89° 15'", description: "The North Star, a yellow-white supergiant used for celestial navigation for centuries." },
  { id: "antares", name: "Antares", type: "star", constellation: "Scorpius", magnitude: 1.06, distance: 550, spectralClass: "M", ra: "16h 29m", dec: "-26° 25'", description: "A red supergiant rivaling Mars in color, marking the heart of Scorpius the Scorpion." },
];

export const observationLogs: ObservationLog[] = [
  { id: "log-1", date: "2026-02-20T21:30:00", objectId: "orion-nebula", objectName: "Orion Nebula", objectType: "nebula", conditions: "excellent", equipment: "Wide-field telescope with nebula filter", notes: "Exceptional detail in the Trapezium region. The nebula filter revealed faint outer wisps extending well beyond the bright core. Seeing was remarkably stable.", quality: 9 },
  { id: "log-2", date: "2026-02-19T22:00:00", objectId: "jupiter", objectName: "Jupiter", objectType: "planet", conditions: "good", equipment: "Schmidt-Cassegrain telescope with tracking mount", notes: "Three Galilean moons visible. The Great Red Spot was just rotating into view. Cloud bands showed excellent contrast.", quality: 8 },
  { id: "log-3", date: "2026-02-18T20:45:00", objectId: "pleiades", objectName: "Pleiades", objectType: "cluster", conditions: "excellent", equipment: "Binoculars", notes: "Stunning view with binoculars. Counted over 40 individual stars. Faint reflection nebulosity visible around the brightest members.", quality: 9 },
  { id: "log-4", date: "2026-02-17T23:15:00", objectId: "andromeda", objectName: "Andromeda Galaxy", objectType: "galaxy", conditions: "fair", equipment: "Large aperture Dobsonian telescope", notes: "Dust lanes visible despite moderate light pollution. The companion galaxies M32 and M110 were both identified.", quality: 6 },
  { id: "log-5", date: "2026-02-16T21:00:00", objectId: "sirius", objectName: "Sirius", objectType: "star", conditions: "good", equipment: "Refractor telescope with high magnification", notes: "Brilliant white with noticeable scintillation due to low altitude. Attempted to split the companion Sirius B without success.", quality: 7 },
  { id: "log-6", date: "2026-02-15T22:30:00", objectId: "saturn", objectName: "Saturn", objectType: "planet", conditions: "excellent", equipment: "Schmidt-Cassegrain telescope with tracking mount", notes: "Ring system beautifully resolved. Cassini Division clearly visible. Titan identified as a bright point nearby.", quality: 10 },
  { id: "log-7", date: "2026-02-14T20:00:00", objectId: "crab-nebula", objectName: "Crab Nebula", objectType: "nebula", conditions: "good", equipment: "Wide-field telescope with nebula filter", notes: "Faint oval glow detected. The nebula filter helped isolate it from the background. No filamentary structure resolved.", quality: 5 },
  { id: "log-8", date: "2026-02-13T23:00:00", objectId: "betelgeuse", objectName: "Betelgeuse", objectType: "star", conditions: "fair", equipment: "Refractor telescope with high magnification", notes: "Distinctly orange-red color confirmed. Magnitude estimate consistent with recent brightening trend.", quality: 6 },
  { id: "log-9", date: "2026-02-12T21:45:00", objectId: "whirlpool", objectName: "Whirlpool Galaxy", objectType: "galaxy", conditions: "poor", equipment: "Large aperture Dobsonian telescope", notes: "Barely visible as a faint smudge. Light pollution and thin cloud cover made this a difficult observation. Spiral arms not resolved.", quality: 3 },
  { id: "log-10", date: "2026-02-11T22:15:00", objectId: "ring-nebula", objectName: "Ring Nebula", objectType: "nebula", conditions: "good", equipment: "Wide-field telescope with nebula filter", notes: "Ring shape clearly visible at medium magnification. Central star not detected. Lovely smoke-ring appearance.", quality: 7 },
  { id: "log-11", date: "2026-02-10T20:30:00", objectId: "mars", objectName: "Mars", objectType: "planet", conditions: "fair", equipment: "Schmidt-Cassegrain telescope with tracking mount", notes: "Small disc showing. Polar ice cap visible as a bright spot. Surface features indistinct due to atmospheric turbulence.", quality: 5 },
  { id: "log-12", date: "2026-02-09T21:00:00", objectId: "hercules-cluster", objectName: "Hercules Cluster", objectType: "cluster", conditions: "excellent", equipment: "Large aperture Dobsonian telescope", notes: "Resolved individual stars across the cluster face. Dense core remained unresolved. Spectacular view at 150x magnification.", quality: 9 },
];

export const plannerSlots: PlannerSlot[] = [
  { id: "slot-1", day: "Monday", time: "21:00", objectName: "Orion Nebula", objectType: "nebula", altitude: 45, azimuth: 180, conditions: "excellent", priority: "high" },
  { id: "slot-2", day: "Monday", time: "23:00", objectName: "Jupiter", objectType: "planet", altitude: 62, azimuth: 210, conditions: "excellent", priority: "critical" },
  { id: "slot-3", day: "Tuesday", time: "20:30", objectName: "Pleiades", objectType: "cluster", altitude: 70, azimuth: 195, conditions: "good", priority: "medium" },
  { id: "slot-4", day: "Wednesday", time: "22:00", objectName: "Andromeda Galaxy", objectType: "galaxy", altitude: 35, azimuth: 290, conditions: "fair", priority: "low" },
  { id: "slot-5", day: "Thursday", time: "21:30", objectName: "Saturn", objectType: "planet", altitude: 28, azimuth: 230, conditions: "good", priority: "high" },
  { id: "slot-6", day: "Friday", time: "23:30", objectName: "Crab Nebula", objectType: "nebula", altitude: 55, azimuth: 170, conditions: "excellent", priority: "medium" },
  { id: "slot-7", day: "Saturday", time: "20:00", objectName: "Halley's Comet", objectType: "comet", altitude: 40, azimuth: 150, conditions: "good", priority: "critical" },
];

export const tonightHighlights = ["sirius", "jupiter", "orion-nebula", "pleiades", "betelgeuse", "saturn"];

export const equipmentGuide = [
  { type: "Refractor Telescope" as const, aperture: "80-120mm", bestFor: "Planets, double stars, lunar observation", description: "Refractor telescopes use lenses to gather light. They produce sharp, high-contrast images ideal for planetary observation and resolving close double stars. A good refractor with high magnification eyepieces is the instrument of choice for detailed lunar and planetary work." },
  { type: "Schmidt-Cassegrain Telescope" as const, aperture: "200-280mm", bestFor: "Planets, galaxies, all-purpose observing", description: "Schmidt-Cassegrain telescopes combine a corrector plate with mirrors to create a compact, versatile instrument. With a tracking mount, they excel at planetary observation and can resolve faint galaxies and nebulae. The long focal length provides high magnification in a portable package." },
  { type: "Dobsonian Telescope" as const, aperture: "250-400mm", bestFor: "Galaxies, nebulae, deep-sky objects", description: "Dobsonian telescopes offer the largest aperture for the lowest cost. The large aperture Dobsonian is the preferred instrument for observing faint galaxies, nebulae, and star clusters. Light-gathering power is paramount for deep-sky observation, and nothing matches a Dobsonian for raw aperture." },
  { type: "Binoculars" as const, aperture: "50-70mm", bestFor: "Star clusters, comets, wide-field scanning", description: "Binoculars provide a wide field of view perfect for scanning the Milky Way, observing star clusters like the Pleiades, and tracking comets. A pair of 10x50 binoculars is an essential tool for every observer, offering portability and an immersive two-eyed viewing experience." },
  { type: "Nebula Filter" as const, aperture: "N/A", bestFor: "Emission nebulae, planetary nebulae", description: "Nebula filters isolate specific wavelengths of light emitted by ionized gas, dramatically improving contrast on emission and planetary nebulae. An O-III or UHC filter transforms the view of objects like the Orion Nebula and Ring Nebula, revealing structure invisible without filtration." },
  { type: "Tracking Mount" as const, aperture: "N/A", bestFor: "Long-exposure observation, astrophotography", description: "A motorized tracking mount compensates for Earth's rotation, keeping celestial objects centered in the eyepiece. Essential for high-magnification planetary observation and astrophotography. Equatorial mounts aligned to the celestial pole provide the most accurate tracking." },
];
